# Generated by Django 3.1.6 on 2021-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('USN', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('MOBILE', models.IntegerField(editable=False)),
                ('EMAIL', models.EmailField(default='', editable=False, max_length=32)),
            ],
        ),
    ]
