# Generated by Django 3.1.6 on 2021-02-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='MOBILE',
            field=models.IntegerField(),
        ),
    ]
