# Generated by Django 3.1 on 2021-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210205_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='MOBILE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='USN',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
